name: Run Nb az_nyse_001.ipynb

on:
  schedule:
    - cron: '0 3 * * SAT'   # 
  workflow_dispatch:       # 수동 실행도 가능

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositoryname
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert papermill
          pip install matplotlib yfinance pandas numpy scipy statsmodels

      - name: Execute notebook
        run: |
          DATE=$(date +'%Y%m%d')
          mkdir -p outputs
          papermill az_nyse_001.ipynb outputs/a_out_${DATE}.ipynb

      - name: Keep only last 5 results
        run: |
          ls -t outputs/a_out_*.ipynb | tail -n +6 | xargs -r rm --

      - name: Commit result to repo
        run: |
          DATE=$(date +'%Y%m%d')
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add outputs/a_out_${DATE}.ipynb
          git add -u outputs
          git commit -m "Add notebook output ${DATE}" || echo "No changes to commit"
          git push

