name: Run Nb az_nyse_001.ipynb

on:
  schedule:
    - cron: '0 22 * * *'   # 매일 KST 07:00 실행 (UTC 22:00)
  workflow_dispatch:       # 수동 실행도 가능

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo_a
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter nbconvert papermill
          pip install matplotlib yfinance pandas numpy scipy statsmodels

      - name: Execute notebook
        run: |
          DATE=$(date +'%Y%m%d')
          mkdir -p test
          papermill az_nyse_001.ipynb test/a_out_${DATE}.ipynb

      - name: Keep only last 5 results
        run: |
          ls -t test/a_out_*.ipynb | tail -n +6 | xargs -r rm --

      - name: Commit result to repo
        run: |
          DATE=$(date +'%Y%m%d')
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add outputs/a_out_${DATE}.ipynb
          git add -u test
          git commit -m "Add notebook output ${DATE}" || echo "No changes to commit"
          git push

